{% set name = "atompaw" %}
{% set version = "4.2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://users.wfu.edu/natalie/papers/pwpaw/{{ name }}-{{ version }}.tar.gz
  sha256: aa8bc4f63f124fdd0f0591596ca6df1b1598d31e8f35d4b951f171165cd96959

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - automake
    - autoconf
    - libtool
  host:
    - libblas
    - liblapack
    - libxc <5.0

test:
  commands:
    - atompaw --help

about:
  home: http://users.wfu.edu/natalie/papers/pwpaw/man.html
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: The software ATOMPAW generates projector and basis functions

  description: |
    The software ATOMPAW generates projector and basis functions which 
    are needed for performing electronic structure calculations 
    (Density-Functional Theory) based on the Projector Augmented Wave (PAW) 
    method.
  doc_url: http://users.wfu.edu/natalie/papers/pwpaw/man.html
  dev_url: https://github.com/atompaw/atompaw

extra:
  recipe-maintainers:
    - jan-janssen
