schema_version: 1

context:
  name: atompaw
  version: "4.2.0.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: http://users.wfu.edu/natalie/papers/pwpaw/${{ name }}-${{ version }}.tar.gz
  sha256: 20dee459f96b06fa6cc1cacd1dad640b841203eda45fe0d9410fa8d70a5052b1

build:
  number: 0
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('fortran') }}
    - make
    - automake
    - autoconf
    - libtool
  host:
    - libblas
    - liblapack
    - libxc <5.0

tests:
  - script:
      - atompaw --help

about:
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: The software ATOMPAW generates projector and basis functions
  description: |
    The software ATOMPAW generates projector and basis functions which
    are needed for performing electronic structure calculations
    (Density-Functional Theory) based on the Projector Augmented Wave (PAW)
    method.
  homepage: http://users.wfu.edu/natalie/papers/pwpaw/man.html
  repository: https://github.com/atompaw/atompaw
  documentation: http://users.wfu.edu/natalie/papers/pwpaw/man.html

extra:
  recipe-maintainers:
    - jan-janssen
